// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evabci/migrationmngr/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryIsMigratingRequest is request type for the Query/IsMigrating RPC method.
type QueryIsMigratingRequest struct {
}

func (m *QueryIsMigratingRequest) Reset()         { *m = QueryIsMigratingRequest{} }
func (m *QueryIsMigratingRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsMigratingRequest) ProtoMessage()    {}
func (*QueryIsMigratingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5ba2bc51c8cb9cb, []int{0}
}
func (m *QueryIsMigratingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMigratingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMigratingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMigratingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMigratingRequest.Merge(m, src)
}
func (m *QueryIsMigratingRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMigratingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMigratingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMigratingRequest proto.InternalMessageInfo

// QueryIsMigratingResponse is response type for the Query/IsMigrating RPC method.
type QueryIsMigratingResponse struct {
	// is_migrating indicates whether a migration is in progress.
	IsMigrating bool `protobuf:"varint,1,opt,name=is_migrating,json=isMigrating,proto3" json:"is_migrating,omitempty"`
	// start_block_height is the block height at which the migration will start.
	StartBlockHeight uint64 `protobuf:"varint,2,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty"`
	// end_block_height is the block height at which the migration will end.
	EndBlockHeight uint64 `protobuf:"varint,3,opt,name=end_block_height,json=endBlockHeight,proto3" json:"end_block_height,omitempty"`
}

func (m *QueryIsMigratingResponse) Reset()         { *m = QueryIsMigratingResponse{} }
func (m *QueryIsMigratingResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsMigratingResponse) ProtoMessage()    {}
func (*QueryIsMigratingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5ba2bc51c8cb9cb, []int{1}
}
func (m *QueryIsMigratingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsMigratingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsMigratingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsMigratingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsMigratingResponse.Merge(m, src)
}
func (m *QueryIsMigratingResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsMigratingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsMigratingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsMigratingResponse proto.InternalMessageInfo

func (m *QueryIsMigratingResponse) GetIsMigrating() bool {
	if m != nil {
		return m.IsMigrating
	}
	return false
}

func (m *QueryIsMigratingResponse) GetStartBlockHeight() uint64 {
	if m != nil {
		return m.StartBlockHeight
	}
	return 0
}

func (m *QueryIsMigratingResponse) GetEndBlockHeight() uint64 {
	if m != nil {
		return m.EndBlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryIsMigratingRequest)(nil), "evabci.migrationmngr.v1.QueryIsMigratingRequest")
	proto.RegisterType((*QueryIsMigratingResponse)(nil), "evabci.migrationmngr.v1.QueryIsMigratingResponse")
}

func init() {
	proto.RegisterFile("evabci/migrationmngr/v1/query.proto", fileDescriptor_e5ba2bc51c8cb9cb)
}

var fileDescriptor_e5ba2bc51c8cb9cb = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0x3b, 0x31,
	0x10, 0xc6, 0x9b, 0xfe, 0xff, 0x8a, 0xa4, 0x22, 0x35, 0x08, 0xad, 0x45, 0x96, 0x5a, 0x11, 0x7b,
	0xb0, 0x1b, 0xab, 0xe0, 0x03, 0xf4, 0xa4, 0x07, 0x41, 0x7b, 0xf4, 0x52, 0xb2, 0xdb, 0x90, 0x86,
	0x76, 0x33, 0xdb, 0x4d, 0x76, 0xa1, 0x57, 0x9f, 0x40, 0x10, 0x1f, 0xc0, 0xb3, 0x2f, 0xe2, 0xb1,
	0xe0, 0xc5, 0xa3, 0xb4, 0x3e, 0x88, 0x34, 0x5b, 0x71, 0xab, 0xec, 0xc1, 0x4b, 0x18, 0xe6, 0xfb,
	0x65, 0xf8, 0xe6, 0x1b, 0x7c, 0xc0, 0x13, 0xe6, 0xf9, 0x92, 0x06, 0x52, 0x44, 0xcc, 0x48, 0x50,
	0x81, 0x12, 0x11, 0x4d, 0xda, 0x74, 0x1c, 0xf3, 0x68, 0xe2, 0x86, 0x11, 0x18, 0x20, 0x95, 0x14,
	0x72, 0x57, 0x20, 0x37, 0x69, 0xd7, 0xb6, 0x59, 0x20, 0x15, 0x50, 0xfb, 0xa6, 0x6c, 0x6d, 0x47,
	0x80, 0x00, 0x5b, 0xd2, 0x45, 0xb5, 0xec, 0xee, 0x09, 0x00, 0x31, 0xe2, 0x94, 0x85, 0x92, 0x32,
	0xa5, 0xc0, 0xd8, 0x31, 0x7a, 0xa9, 0xe6, 0x9a, 0x30, 0x93, 0x90, 0x2f, 0xa1, 0xc6, 0x2e, 0xae,
	0xdc, 0x2c, 0x3c, 0x5d, 0xea, 0xab, 0x14, 0x53, 0xa2, 0xcb, 0xc7, 0x31, 0xd7, 0xa6, 0xf1, 0x88,
	0x70, 0xf5, 0xb7, 0xa6, 0x43, 0x50, 0x9a, 0x93, 0x7d, 0xbc, 0x29, 0x75, 0x2f, 0xf8, 0xea, 0x57,
	0x51, 0x1d, 0x35, 0x37, 0xba, 0x25, 0xf9, 0x8d, 0x92, 0x63, 0x4c, 0xb4, 0x61, 0x91, 0xe9, 0x79,
	0x23, 0xf0, 0x87, 0xbd, 0x01, 0x97, 0x62, 0x60, 0xaa, 0xc5, 0x3a, 0x6a, 0xfe, 0xef, 0x96, 0xad,
	0xd2, 0x59, 0x08, 0x17, 0xb6, 0x4f, 0x9a, 0xb8, 0xcc, 0x55, 0x7f, 0x95, 0xfd, 0x67, 0xd9, 0x2d,
	0xae, 0xfa, 0x19, 0xf2, 0xf4, 0x19, 0xe1, 0x35, 0xeb, 0x8b, 0x3c, 0x21, 0x5c, 0xca, 0x98, 0x23,
	0x27, 0x6e, 0x4e, 0xa4, 0x6e, 0xce, 0x8e, 0xb5, 0xf6, 0x1f, 0x7e, 0xa4, 0x9b, 0x37, 0x5a, 0x77,
	0xaf, 0x1f, 0x0f, 0xc5, 0x23, 0x72, 0x48, 0xf3, 0xf2, 0xcd, 0x06, 0xd3, 0xb9, 0x7e, 0x99, 0x39,
	0x68, 0x3a, 0x73, 0xd0, 0xfb, 0xcc, 0x41, 0xf7, 0x73, 0xa7, 0x30, 0x9d, 0x3b, 0x85, 0xb7, 0xb9,
	0x53, 0xb8, 0x3d, 0x17, 0xd2, 0x0c, 0x62, 0xcf, 0xf5, 0x21, 0xa0, 0x3c, 0xd1, 0x86, 0xf9, 0x43,
	0xca, 0x93, 0x56, 0x3a, 0x13, 0xfa, 0xf1, 0x88, 0xeb, 0x1f, 0xb3, 0xed, 0xe1, 0xbc, 0x75, 0x7b,
	0xb9, 0xb3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xa6, 0xa6, 0xe3, 0x65, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// IsMigrating queries whether a migration is in progress.
	IsMigrating(ctx context.Context, in *QueryIsMigratingRequest, opts ...grpc.CallOption) (*QueryIsMigratingResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) IsMigrating(ctx context.Context, in *QueryIsMigratingRequest, opts ...grpc.CallOption) (*QueryIsMigratingResponse, error) {
	out := new(QueryIsMigratingResponse)
	err := c.cc.Invoke(ctx, "/evabci.migrationmngr.v1.Query/IsMigrating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// IsMigrating queries whether a migration is in progress.
	IsMigrating(context.Context, *QueryIsMigratingRequest) (*QueryIsMigratingResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) IsMigrating(ctx context.Context, req *QueryIsMigratingRequest) (*QueryIsMigratingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsMigrating not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_IsMigrating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsMigratingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsMigrating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evabci.migrationmngr.v1.Query/IsMigrating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsMigrating(ctx, req.(*QueryIsMigratingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evabci.migrationmngr.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsMigrating",
			Handler:    _Query_IsMigrating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evabci/migrationmngr/v1/query.proto",
}

func (m *QueryIsMigratingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMigratingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMigratingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIsMigratingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsMigratingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsMigratingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndBlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EndBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartBlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.IsMigrating {
		i--
		if m.IsMigrating {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryIsMigratingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIsMigratingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsMigrating {
		n += 2
	}
	if m.StartBlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.StartBlockHeight))
	}
	if m.EndBlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.EndBlockHeight))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryIsMigratingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMigratingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMigratingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsMigratingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsMigratingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsMigratingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMigrating", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMigrating = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlockHeight", wireType)
			}
			m.StartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlockHeight", wireType)
			}
			m.EndBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
