// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evabci/migrationmngr/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgMigrate is the Msg/Migrate request type.
type MsgMigrate struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// block height that triggers the migration.
	// When IBC is enabled, the migration can take several blocks to complete.
	// This is the block height at which the migration will be triggered.
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// sequencer is the pubkey that will become new sequencer.
	Sequencer Sequencer `protobuf:"bytes,3,opt,name=sequencer,proto3" json:"sequencer"`
}

func (m *MsgMigrate) Reset()         { *m = MsgMigrate{} }
func (m *MsgMigrate) String() string { return proto.CompactTextString(m) }
func (*MsgMigrate) ProtoMessage()    {}
func (*MsgMigrate) Descriptor() ([]byte, []int) {
	return fileDescriptor_33fc897f55490d9b, []int{0}
}
func (m *MsgMigrate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMigrate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMigrate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMigrate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMigrate.Merge(m, src)
}
func (m *MsgMigrate) XXX_Size() int {
	return m.Size()
}
func (m *MsgMigrate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMigrate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMigrate proto.InternalMessageInfo

func (m *MsgMigrate) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgMigrate) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgMigrate) GetSequencer() Sequencer {
	if m != nil {
		return m.Sequencer
	}
	return Sequencer{}
}

// MsgMigrateResponse defines the response structure for executing a
// MsgMigrate message.
type MsgMigrateResponse struct {
}

func (m *MsgMigrateResponse) Reset()         { *m = MsgMigrateResponse{} }
func (m *MsgMigrateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMigrateResponse) ProtoMessage()    {}
func (*MsgMigrateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33fc897f55490d9b, []int{1}
}
func (m *MsgMigrateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMigrateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMigrateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMigrateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMigrateResponse.Merge(m, src)
}
func (m *MsgMigrateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMigrateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMigrateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMigrateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgMigrate)(nil), "evabci.migrationmngr.v1.MsgMigrate")
	proto.RegisterType((*MsgMigrateResponse)(nil), "evabci.migrationmngr.v1.MsgMigrateResponse")
}

func init() { proto.RegisterFile("evabci/migrationmngr/v1/tx.proto", fileDescriptor_33fc897f55490d9b) }

var fileDescriptor_33fc897f55490d9b = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4b, 0xf3, 0x40,
	0x18, 0xc7, 0x73, 0x6f, 0xdf, 0xf7, 0x95, 0x5c, 0x5d, 0x0c, 0x85, 0xc6, 0x08, 0x31, 0xb6, 0x4b,
	0xa9, 0x34, 0x47, 0x2b, 0x74, 0x70, 0xb3, 0x93, 0x20, 0x05, 0x49, 0x37, 0x1d, 0x4a, 0x92, 0x1e,
	0x97, 0xa3, 0x4d, 0xae, 0xe6, 0x2e, 0xc1, 0x6e, 0xe2, 0xe8, 0xe4, 0xc7, 0x70, 0xec, 0xe0, 0x87,
	0xe8, 0x58, 0x9c, 0x9c, 0x44, 0x5a, 0xa1, 0x5f, 0x43, 0x9a, 0xa4, 0x04, 0x95, 0x82, 0xcb, 0x71,
	0xcf, 0xff, 0xf9, 0x3d, 0xf7, 0x3c, 0xcf, 0xfd, 0xa1, 0x81, 0x63, 0xdb, 0x71, 0x29, 0xf2, 0x29,
	0x09, 0x6d, 0x41, 0x59, 0xe0, 0x07, 0x24, 0x44, 0x71, 0x13, 0x89, 0x5b, 0x73, 0x1c, 0x32, 0xc1,
	0x94, 0x72, 0x4a, 0x98, 0x5f, 0x08, 0x33, 0x6e, 0x6a, 0x7b, 0xb6, 0x4f, 0x03, 0x86, 0x92, 0x33,
	0x65, 0xb5, 0xb2, 0xcb, 0xb8, 0xcf, 0x38, 0xf2, 0x39, 0x59, 0xbf, 0xe1, 0x73, 0x92, 0x25, 0xf6,
	0xd3, 0x44, 0x3f, 0x89, 0x50, 0x1a, 0x64, 0xa9, 0x12, 0x61, 0x84, 0xa5, 0xfa, 0xfa, 0x96, 0xa9,
	0xd5, 0xad, 0x73, 0x4d, 0xc6, 0x38, 0x2b, 0xad, 0x7c, 0x00, 0x08, 0xbb, 0x9c, 0x74, 0x13, 0x06,
	0x2b, 0x6d, 0x28, 0xdb, 0x91, 0xf0, 0x58, 0x48, 0xc5, 0x44, 0x05, 0x06, 0xa8, 0xc9, 0x1d, 0xf5,
	0xe5, 0xb9, 0x51, 0xca, 0xda, 0x9d, 0x0d, 0x06, 0x21, 0xe6, 0xbc, 0x27, 0x42, 0x1a, 0x10, 0x2b,
	0x47, 0x95, 0x23, 0xb8, 0xeb, 0x8c, 0x98, 0x3b, 0xec, 0x7b, 0x98, 0x12, 0x4f, 0xa8, 0x7f, 0x0c,
	0x50, 0xfb, 0x6b, 0x15, 0x13, 0xed, 0x3c, 0x91, 0x94, 0x0b, 0x28, 0x73, 0x7c, 0x13, 0xe1, 0xc0,
	0xc5, 0xa1, 0x5a, 0x30, 0x40, 0xad, 0xd8, 0xaa, 0x98, 0x5b, 0x3e, 0xc6, 0xec, 0x6d, 0xc8, 0x8e,
	0x3c, 0x7b, 0x3b, 0x94, 0x9e, 0x56, 0xd3, 0x3a, 0xb0, 0xf2, 0xfa, 0x53, 0xf3, 0x7e, 0x35, 0xad,
	0xe7, 0xfd, 0x1f, 0x56, 0xd3, 0xfa, 0xc1, 0x8f, 0x3d, 0xf3, 0xbd, 0x2a, 0x25, 0xa8, 0xe4, 0x91,
	0x85, 0xf9, 0x98, 0x05, 0x1c, 0xb7, 0x28, 0x2c, 0x74, 0x39, 0x51, 0xae, 0xe1, 0xce, 0x66, 0xff,
	0xea, 0xd6, 0x89, 0xf2, 0x72, 0xed, 0xf8, 0x17, 0xd0, 0xa6, 0x87, 0xf6, 0xef, 0x6e, 0x3d, 0x7b,
	0xe7, 0x72, 0xb6, 0xd0, 0xc1, 0x7c, 0xa1, 0x83, 0xf7, 0x85, 0x0e, 0x1e, 0x97, 0xba, 0x34, 0x5f,
	0xea, 0xd2, 0xeb, 0x52, 0x97, 0xae, 0xda, 0x84, 0x0a, 0x2f, 0x72, 0x4c, 0x97, 0xf9, 0x08, 0xc7,
	0x5c, 0xd8, 0xee, 0x10, 0xe1, 0xb8, 0x91, 0x5a, 0xc7, 0x06, 0xd1, 0x08, 0xf3, 0x6f, 0x16, 0x26,
	0xfe, 0x39, 0xff, 0x13, 0x03, 0x4f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x0a, 0xf6, 0x6f,
	0x7f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Migrate defines a (governance) operation for unbonding validators. The authority defaults to the x/gov module account.
	Migrate(ctx context.Context, in *MsgMigrate, opts ...grpc.CallOption) (*MsgMigrateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Migrate(ctx context.Context, in *MsgMigrate, opts ...grpc.CallOption) (*MsgMigrateResponse, error) {
	out := new(MsgMigrateResponse)
	err := c.cc.Invoke(ctx, "/evabci.migrationmngr.v1.Msg/Migrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Migrate defines a (governance) operation for unbonding validators. The authority defaults to the x/gov module account.
	Migrate(context.Context, *MsgMigrate) (*MsgMigrateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Migrate(ctx context.Context, req *MsgMigrate) (*MsgMigrateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMigrate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evabci.migrationmngr.v1.Msg/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Migrate(ctx, req.(*MsgMigrate))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evabci.migrationmngr.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _Msg_Migrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evabci/migrationmngr/v1/tx.proto",
}

func (m *MsgMigrate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMigrate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMigrate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Sequencer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMigrateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMigrateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMigrateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgMigrate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	l = m.Sequencer.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgMigrateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgMigrate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMigrate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMigrate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequencer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMigrateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMigrateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMigrateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
