// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evabci/migrationmngr/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Migration defines the migration state for unbonding validators.
type Migration struct {
	// block height that triggers the migration.
	// When IBC is enabled, the migration can take several blocks to complete.
	// This is the block height at which the migration will be triggered.
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// sequencer is the pubkey that will become new sequencer.
	Sequencer Sequencer `protobuf:"bytes,3,opt,name=sequencer,proto3" json:"sequencer"`
}

func (m *Migration) Reset()         { *m = Migration{} }
func (m *Migration) String() string { return proto.CompactTextString(m) }
func (*Migration) ProtoMessage()    {}
func (*Migration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2804a23bbabbd69, []int{0}
}
func (m *Migration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Migration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Migration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Migration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Migration.Merge(m, src)
}
func (m *Migration) XXX_Size() int {
	return m.Size()
}
func (m *Migration) XXX_DiscardUnknown() {
	xxx_messageInfo_Migration.DiscardUnknown(m)
}

var xxx_messageInfo_Migration proto.InternalMessageInfo

func (m *Migration) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Migration) GetSequencer() Sequencer {
	if m != nil {
		return m.Sequencer
	}
	return Sequencer{}
}

// Sequencer defines a sequencer that can validate blocks.
type Sequencer struct {
	// name is the human-readable name of the sequencer.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// consensus_pubkey is the consensus public key of the sequencer, as a
	// Protobuf Any.
	ConsensusPubkey *types.Any `protobuf:"bytes,2,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty"`
}

func (m *Sequencer) Reset()         { *m = Sequencer{} }
func (m *Sequencer) String() string { return proto.CompactTextString(m) }
func (*Sequencer) ProtoMessage()    {}
func (*Sequencer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2804a23bbabbd69, []int{1}
}
func (m *Sequencer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sequencer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sequencer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sequencer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sequencer.Merge(m, src)
}
func (m *Sequencer) XXX_Size() int {
	return m.Size()
}
func (m *Sequencer) XXX_DiscardUnknown() {
	xxx_messageInfo_Sequencer.DiscardUnknown(m)
}

var xxx_messageInfo_Sequencer proto.InternalMessageInfo

func (m *Sequencer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sequencer) GetConsensusPubkey() *types.Any {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

func init() {
	proto.RegisterType((*Migration)(nil), "evabci.migrationmngr.v1.Migration")
	proto.RegisterType((*Sequencer)(nil), "evabci.migrationmngr.v1.Sequencer")
}

func init() {
	proto.RegisterFile("evabci/migrationmngr/v1/types.proto", fileDescriptor_c2804a23bbabbd69)
}

var fileDescriptor_c2804a23bbabbd69 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0xcd, 0xbc, 0x57, 0x1e, 0x24, 0x7d, 0xf0, 0x9e, 0xa1, 0x60, 0xec, 0x22, 0xd6, 0xba, 0x29,
	0x42, 0x67, 0x68, 0x05, 0xf7, 0x76, 0x25, 0x14, 0xa1, 0xc4, 0x95, 0x6e, 0x4a, 0x32, 0x5e, 0xa7,
	0xa1, 0xcd, 0xdc, 0x98, 0x49, 0x02, 0xd1, 0x9f, 0xf0, 0x33, 0x5c, 0xba, 0xf0, 0x23, 0x8a, 0xab,
	0x2e, 0x5d, 0x89, 0xb4, 0x0b, 0x7f, 0x43, 0x9c, 0x34, 0x15, 0x05, 0x37, 0xe1, 0xde, 0x73, 0x4e,
	0xee, 0x9c, 0xc3, 0xb1, 0xf6, 0x21, 0xf7, 0x03, 0x1e, 0xb2, 0x28, 0x14, 0x89, 0x9f, 0x86, 0x28,
	0x23, 0x29, 0x12, 0x96, 0xf7, 0x58, 0x5a, 0xc4, 0xa0, 0x68, 0x9c, 0x60, 0x8a, 0xf6, 0x76, 0x29,
	0xa2, 0x5f, 0x44, 0x34, 0xef, 0x35, 0xb7, 0xfc, 0x28, 0x94, 0xc8, 0xf4, 0xb7, 0xd4, 0x36, 0x1b,
	0x02, 0x05, 0xea, 0x91, 0x7d, 0x4c, 0x6b, 0x74, 0x87, 0xa3, 0x8a, 0x50, 0x8d, 0x4b, 0xa2, 0x5c,
	0x2a, 0x4a, 0x20, 0x8a, 0x19, 0x30, 0xbd, 0x05, 0xd9, 0x15, 0xf3, 0x65, 0x51, 0x52, 0xed, 0x5b,
	0xcb, 0x3c, 0xad, 0x9e, 0xb4, 0xf7, 0xac, 0xbf, 0xc1, 0x0c, 0xf9, 0x74, 0x3c, 0x81, 0x50, 0x4c,
	0x52, 0xe7, 0x57, 0x8b, 0x74, 0x6a, 0x5e, 0x5d, 0x63, 0x27, 0x1a, 0xb2, 0x87, 0x96, 0xa9, 0xe0,
	0x3a, 0x03, 0xc9, 0x21, 0x71, 0x7e, 0xb7, 0x48, 0xa7, 0xde, 0x6f, 0xd3, 0x1f, 0xbc, 0xd3, 0xb3,
	0x4a, 0x39, 0x30, 0xe7, 0x2f, 0xbb, 0xc6, 0xfd, 0xdb, 0xc3, 0x01, 0xf1, 0x3e, 0xff, 0x6f, 0xdf,
	0x58, 0xe6, 0x46, 0x62, 0xdb, 0x56, 0x4d, 0xfa, 0x11, 0x38, 0xa4, 0x45, 0x3a, 0xa6, 0xa7, 0x67,
	0xfb, 0xdc, 0xfa, 0xcf, 0x51, 0x2a, 0x90, 0x2a, 0x53, 0xe3, 0x38, 0x0b, 0xa6, 0x50, 0x68, 0x53,
	0xf5, 0x7e, 0x83, 0x96, 0x99, 0x68, 0x95, 0x89, 0x1e, 0xcb, 0x62, 0xe0, 0x3c, 0x3d, 0x76, 0x1b,
	0xeb, 0xe8, 0x3c, 0x29, 0xe2, 0x14, 0xe9, 0x28, 0x0b, 0x86, 0x50, 0x78, 0xff, 0x36, 0x77, 0x46,
	0xfa, 0xcc, 0x60, 0x34, 0x5f, 0xba, 0x64, 0xb1, 0x74, 0xc9, 0xeb, 0xd2, 0x25, 0x77, 0x2b, 0xd7,
	0x58, 0xac, 0x5c, 0xe3, 0x79, 0xe5, 0x1a, 0x17, 0x47, 0x22, 0x4c, 0x27, 0x59, 0x40, 0x39, 0x46,
	0x0c, 0x72, 0x95, 0xfa, 0x7c, 0xca, 0x20, 0xef, 0x96, 0x1d, 0xe2, 0x65, 0x36, 0x03, 0xf5, 0xad,
	0x4b, 0x5d, 0x64, 0xf0, 0x47, 0x5b, 0x39, 0x7c, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x1f, 0x90,
	0x11, 0xf0, 0x01, 0x00, 0x00,
}

func (m *Migration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Migration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Migration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Sequencer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.BlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *Sequencer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sequencer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sequencer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsensusPubkey != nil {
		{
			size, err := m.ConsensusPubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Migration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.BlockHeight))
	}
	l = m.Sequencer.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *Sequencer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ConsensusPubkey != nil {
		l = m.ConsensusPubkey.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Migration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Migration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Migration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequencer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Sequencer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sequencer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sequencer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = &types.Any{}
			}
			if err := m.ConsensusPubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
